project:
  type: book

book:
  title: "Probability and Statistics: a simulation-based approach"
  author: "Bob Carpenter and Brian Ward"
  date: "2022-08-04"
  search: true
  repo-url: https://github.com/bob-carpenter/prob-stats
  repo-actions: [edit]
#  downloads: [pdf, epub]
#  sharing: [twitter]
  page-navigation: false
#  navbar:
#    search: true
  chapters:
    - index.qmd
    - intro.qmd
    - random-variables.qmd
    - expectation.qmd
    - event-probabilities.qmd
#    - probability-mass-functions.qmd
#    - continuous-random-variables.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
    mainfont: palatino
    number-depth: 2
    page-layout: full
  pdf:
    documentclass: scrreprt



