project:
  type: book

book:
  title: "Probability and Statistics: a simulation-based approach"
  author: "Bob Carpenter and Brian Ward"
  date: "2022-08-04"
  chapters:
    - index.qmd
    - intro.qmd
    - random-variables.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    mainfont: palatino
    number-depth: 2
    page-layout: full
  pdf:
    documentclass: scrreprt



